### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xor256** [bararchy/crystal-fann#10]
```
make cr
crystal run ./fa2.cr
F-ann5858T-rainD-ata.o: In function `set_train_struct':
/home/xor256/t1a-fann/lib/crystal-fann/src/crystal-fann/train_data.cr:21: undefined reference to `fann_create_train_pointer_array'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `sqrtf'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `log'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `exp'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `sin'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `pow'
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libdoublefann.so: undefined reference to `cos'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/xor256/.cache/crystal/crystal-run-fa2.tmp'  -rdynamic  -ldoublefann -lpcre /usr/bin/../lib/crystal/lib/libgc.a -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/bin/../lib/crystal/lib -L/usr/lib -L/usr/local/lib`
make: *** [Makefile:5: cr] Błąd 1

```
fedora 30

trouble with simplest in static mode --release --static

/```
usr/bin/ld: cannot find -ldoublefann (this usually means you need to install the development package for libdoublefann)
/usr/bin/ld: cannot find -lpcre (this usually means you need to install the development package for libpcre)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/xor/fa1'  -rdynamic -static  -ldoublefann -lpcre -lm /usr/bin/../lib/crystal/lib/libgc.a -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/bin/../lib/crystal/lib -L/usr/lib -L/usr/local/lib`
```

**Comment by bararchy** [comment]
Hi @xor256 , It seems your installation is missing the `libdoublefann` and `libpcre` with the relevant development headers.
I would suggest following the instructions here: https://github.com/libfann/fann#to-install to install the lib from source, this should allow you to use all functionality.

Also make sure to install the libpcre lib

**Comment by bararchy** [comment]
@xor256 I would also suggest that you maybe try out https://github.com/NeuraLegion/shainet which is pure crystal (won't need other dependencies) and will maybe answer your needs.

The libfann project (c lib) is pretty much dead, or was so when I last checked, so this shard won't be updated as it's a bit of a useless effort
