### ISSUE TITLE
to C

### ISSUE THREAD

**Issue by fab1an2** [bararchy/crystal-fann#11]
Is possible add a function to generate C program without dependencies?
For example I put data, learn in Crystal, but at end I get one simple finction in C

#define WEIGHTS ....
int result(data *input.....)
{
}

ideal for embeded, no dependencies, no load any file. Only put input and get output

**Comment by bararchy** [comment]
Well, FANN is originally a C librery, I don't see the point in writing in Crystal, then export it to C if you already have C that does the same :) 

maybe I didn't understand your use case though

**Comment by bararchy** [comment]
@fab1an2 -> https://github.com/crystal-lang/crystal/issues/921

**Comment by fab1an2** [comment]
not this same
Why I must load weights? Why I must using file to store bias etc?

No problem You can generating Crystal code
but one function to predict answer.
On last You dont needed learning, data etc. 
only get output/solution
