### ISSUE TITLE
Doesn't compile on Crystal 0.36.0, due to `require "logger"`

### ISSUE THREAD

**Issue by oprypin** [bararchy/crystal-fann#12]
See e.g. https://github.com/oprypin/game-bots/runs/1771874849

**Comment by oprypin** [comment]
I still get a notification every week that my CI is failing :D
https://github.com/oprypin/game-bots/actions
https://github.com/oprypin/game-bots/runs/4339737681?check_suite_focus=true
@bararchy

**Comment by bararchy** [comment]
@oprypin sorry :grin: 
https://github.com/NeuraLegion/crystal-fann/releases/tag/v1.2.0
Should work on 1.2.2 perfectly, let me know if there are any issues

**Comment by oprypin** [comment]
Nice nice nice. Thanks much!
