### ISSUE TITLE
Need to add save to file and load from file methods to networks

### ISSUE THREAD

**Issue by bararchy** [bararchy/crystal-fann#7]
@hugoabonizio Wana try and tackle this ? 

To allow long runs and reuse of the trained network later, we need to add `.save` and `.load` options, basically it just uses 
```crystal
fun save = fann_save(ann : Fann*, configuration_file : LibC::Char*) : LibC::Int
fun create_from_file = fann_create_from_file(configuration_file : LibC::Char*) : Fann*
```

so something along the lines of 
```crystal
def save(path : String) : Int32
  LibFANN.save(@ann, path)
end
```
and something similar for load, crate_from_file

**Comment by hugoabonizio** [comment]
Done in #8 :smiley:
